name: zcvoter
description: "Zcash Vote App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+6

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  convert: ^3.1.1
  rust_lib_zcvoter:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  logger: ^2.0.2+1
  go_router: ^14.8.1
  flutter_mobx: ^2.0.2
  mobx: ^2.2.1
  gap: ^3.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  freezed_annotation: any
  path_provider: ^2.1.5
  awesome_dialog: ^3.2.1
  toastification: ^3.0.2
  showcaseview: ^4.0.1
  mobile_scanner: ^6.0.7
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.2
  mobx_codegen: ^2.7.0
  freezed: ^2.5.7

  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

