// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'election.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> createDirectoryDb({required String directory}) =>
    RustLib.instance.api
        .crateApiElectionCreateDirectoryDb(directory: directory);

Future<void> connectElection({required String url}) =>
    RustLib.instance.api.crateApiElectionConnectElection(url: url);

Future<List<ElectionRec>> listElections() =>
    RustLib.instance.api.crateApiElectionListElections();

@freezed
class ElectionRec with _$ElectionRec {
  const factory ElectionRec({
    required PlatformInt64 id,
    required String hash,
    required String name,
    required String question,
  }) = _ElectionRec;
}
